language: python
python:
  - "2.7"
install:
  - pip install -r test_requirements.txt --use-mirrors
  - pip install flake8 --use-mirrors
  - pip install -q . --use-mirrors
before_script:
  - flake8 setup.py akanda --ignore=E123,E133,E226,E241,E242,E731
script: nosetests -d